// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 创建一个统一的侧边栏 (名字可以自定义，例如 'tutorialSidebar' 或 'docsSidebar')
  tutorialSidebar: [
    {
      type: 'category',
      label: 'SWAPX INTEGRATION',
      collapsible: false,
      collapsed: false,
      className: 'top-level-category',
      items: [
        {
          type: 'autogenerated',
          dirName: 'swapx-integration',
        },
      ],
    },
    {
      type: 'category',
      label: 'SWAPX DEVELOPER',
      collapsible: false,
      collapsed: false,
      className: 'top-level-category',
      items: [
        {
          type: 'autogenerated',
          dirName: 'swapx-developer',
        },
      ],
    },

  ],
};

export default sidebars;