// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 创建一个统一的侧边栏 (名字可以自定义，例如 'tutorialSidebar' 或 'docsSidebar')
  tutorialSidebar: [
    {
      type: 'category',
      label: 'SWAPX INTEGRATION',
      collapsible: false,
      collapsed: false,
      className: 'top-level-category',
      items: [
        {
          type: 'autogenerated',
          dirName: 'swapx-integration',
        },
      ],
    },
    // {
    //   type: 'category',
    //   label: 'STUDY',
    //   collapsible: false,
    //   collapsed: false,
    //   className: 'top-level-category',
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'study',
    //     },
    //   ],
    // },
    {
      type: 'category',
      label: 'CONTRACT',
      collapsible: false,
      collapsed: false,
      className: 'top-level-category',
      items: [
        {
          type: 'autogenerated',
          dirName: 'contract',
        },
      ],
    },
    {
      type: 'category',
      label: 'SDK',
      collapsible: false,
      collapsed: false,
      className: 'top-level-category',
      items: [
        {
          type: 'autogenerated',
          dirName: 'sdk',
        },
      ],
    },

  ],
};

export default sidebars;